feat: 마이페이지에서 사용자의 게임 전적을 조회한다.
snack-game/server pull request #114
Opened 2024-03-11 06:44 UTC by Hwanvely

## 관련 이슈
- #113 
- resolves: #113 

## 변경 사항
### AS-IS
이전에는 랭킹 내에서만 최고점수와 순위를 확인 할 수 있었다.

### TO-BE
최근 진행한 25게임의 점수 및 최근 1주일 내 각각 날짜의 최고 점수를 확인 할 수 있다.

---
## 추가 변경 사항
### AS-IS
랭킹에서 순위, 점수, 사용자 이름 및 그룹만 확인 가능하였다. 
```
{
    "rank": 0,
    "score": 0,
    "owner": {
      "id": 0,
      "name": "string",
      "group": {
        "id": 2,
        "name": "숭실대학교"
      }
    }
  }
```
### TO-BE
사용자의 레벨도 추가로 조회할 수 있다.
```
{
    "rank": 0,
    "score": 0,
    "owner": {
      "id": 0,
      "name": "string",
      "level": 0,
      "group": {
        "id": 2,
        "name": "숭실대학교"
      }
    }
  }
```

2024-03-11 06:59 UTC, Hwanvely commented
게임 전적을 조회 할 시에 `SeasonId`를 받아 시즌 별로 조회하는 것은 꽤 큰 공사가 될 것 같아 의견을 구합니다.


> 현재 게임 전적 조회는 `AppleGame`테이블을 사용하고 있는데 여기에는 `Season`에 대한 정보가 없습니다.

2024-03-18 02:11 UTC, 0chil requested changes
꼼꼼한 테스트까지 너무 고생하셨습니다~! 
신경써야할 부분 2개만 리뷰 남겼습니다.

2024-03-18 02:11 UTC, 0chil commented on src/main/java/com/snackgame/server/history/dao/GameHistoryDao.java
> +    private static final LocalDate PREVIOUS_DATE = LocalDate.now().minus(7, ChronoUnit.DAYS);
PREVIOUS_DATE는 static 변수라서 클래스 로드시에 만들어지기 때문에 며칠이 지나면 7일전.. 8일전.. 점점 늘어날 것 같습니다.
수정이 필요해보여요

2024-03-18 02:11 UTC, 0chil commented on src/main/java/com/snackgame/server/history/controller/GameHistoryController.java
> +}
```suggestion
    @GetMapping("/histories/me")
    @Operation(summary = "자신의 게임 전적 조회", description = "최근 7일 동안의 최고 점수를 조회한다.")
    public List<GameHistoryResponse> showHistoriesBy(@Authenticated Member member, String by) {
        if(by== ~~){
        return gameHistoryDao.selectByDate(member.getId());
        }
        return gameHistoryDao.selectBySession(member.getId(), GAME_RECORD_SIZE);
    }
}
```

요로케 API를 하나로 통합하는 방안 어떠신가용

2024-03-18 02:50 UTC, merged