refactor: 레거시 제거
snack-game/server pull request #137
Opened 2024-04-18 10:28 UTC by Hwanvely

## 변경 사항
### AS-IS

1. '쿠키 토큰'으로 이전한 후 하위호환성을 고려하여 '헤더 토큰'을 허용해 두었습니다.
2. GracefulShutdown의 테스트를 위하여 `Test`컨트롤러를 만들어 두었습니다.
3. `AppleGame` 테이블에 게임의 종료 여부를 판단하기 위한 플래그(`is_ended`, `is_finished`)가 존재하였습니다.

### TO-BE

1. 현재는 더이상 '헤더 토큰'을 발급받은 사용자가 없기에 '쿠키 토큰'만 허용해두었습니다.
2. 테스트가 통과되었기에 불필요한 컨트롤러를 제거하였습니다.
3. `FinishedAt`이라는 명확한 시간으로 종료를 판단하기에 플래그들은 제거하였습니다.

2024-04-18 13:53 UTC, 0chil requested changes
Wow! 예상치 못한 pr 아주 좋습니다
문제가 생길 수 있는 부분에 커멘트 하나 남겼어요

2024-04-18 13:53 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
> +        String cookieToken = foundCookie.get().getValue();
이렇게 했을때 쿠키가 없으면 어떻게될까요?

2024-04-19 06:42 UTC, Hwanvely commented on src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
> +        String cookieToken = foundCookie.get().getValue();
<img width="712" alt="스크린샷 2024-04-19 오후 3 41 09" src="https://github.com/snack-game/server/assets/122357140/6a7bd845-7ca7-4324-b87a-d86e2023dabc">

현재 위와 같이 `request`에서 쿠리를 처리하고있긴한데 이것으로는 처리가 부족할까요?

2024-04-19 07:14 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
> +        String cookieToken = foundCookie.get().getValue();
네. 쿠키가 없는 경우 NPE가 발생합니다.
`Optional.empty().get().getValue()`하면 어떻게 되는지 생각해보시면 될 것 같네요.
아무 요청이나 쿠키 없이 보내보시면 알 수 있습니다.

'Optional은 '값이 없음'에 대한 예외처리를 사용측에 위임하기 위해 사용한다'라는 점을 참고하시면 좋을 것 같네요.

2024-04-19 07:20 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/support/JwtMemberArgumentResolver.java
> +        String cookieToken = foundCookie.get().getValue();
참고로 첨부해주신 메서드는 '쿠키 배열'에 대한 null 처리만 수행하고 있습니다.

2024-04-22 03:22 UTC, 0chil approved these changes

2024-04-22 03:23 UTC, merged