Feature/logout
snack-game/server pull request #91
Opened 2024-01-23 07:24 UTC by Hwanvely

## AS IS

원래는 엑세스 토큰만 사용하여 엑세스 토큰을 만료시키는 방식으로 로그아웃을 진행하였다.
하지만 리프레시 토큰이 생기고 리프레시 토큰을 만료시킬 방안이 필요했다.

## TO BE

로그아웃 API를 만들어 리프레시 토큰을 삭제(Soft-Delete)하고 
쿠키에서 리프레시 토큰을 제거하고 maxAge를 0으로 초기화하여 만료시키도록 하였다.

2024-01-23 07:44 UTC, 0chil requested changes
고생하셨습니다~! 사소한 커멘트 몇 개 남겼습니다!

2024-01-23 07:44 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/TokenService.java
> +    private long refreshTokenExpiry;
요건 상수의 성격을 가지니까 위로 올려서 구분하면 좋을 것 같아열

2024-01-23 07:44 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/TokenService.java
> +    }
저희는 블랙리스트를 (아직) 따로 운영하고 있지는 않은데요.
그래서 삭제의 의미를 주는 메서드명 정도로 하면 어떨까 제안드려봅니다

2024-01-23 07:44 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
> +    @Column(name = "refresh_token_id", updatable = false)
현재 운영 서버에 'id'라는 컬럼명으로 배포가 되어있는데요!
별도로 refresh_token_id로 바꿔주신 이유가 궁금합니다.

2024-01-23 07:44 UTC, 0chil commented on src/main/java/com/snackgame/server/member/controller/AuthController.java
>          TokenDto reissued = tokenService.reissueFrom(refreshToken);
💯

2024-01-23 07:44 UTC, 0chil commented on src/main/java/com/snackgame/server/member/controller/AuthController.java
> +                                .maxAge(0)
이건 `Duration.Zero`를 활용해서 의미를 좀 더 명확하게 전달할 수 있을 것 같네요!

2024-01-23 07:44 UTC, 0chil commented on src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
> +        Cookie refresh_cookie = RestAssured.given()
변수를 컨벤션에 맞춰 snakeCase로 작성해주세요!

2024-01-23 07:44 UTC, 0chil commented on src/test/java/com/snackgame/server/member/controller/AuthControllerTest.java
> +        assertThat(refreshTokenRepository.findAll()).hasSize(1);
'토큰 발급 검증' 부분과 '토큰 제거 검증' 부분을 두개의 테스트로 나누면 어떨까요?
지금은 한 메서드에서 두 개 다 검증하려다 보니까 살짝 복잡해지는 감이 있네용

2024-01-23 07:57 UTC, Hwanvely commented on src/main/java/com/snackgame/server/auth/token/TokenService.java
> +    }
좋습니다. deleteBy는 어떠신가요?

2024-01-23 07:57 UTC, Hwanvely commented on src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
> +    @Column(name = "refresh_token_id", updatable = false)
논의했던부분에서 나온 생각인데 후에 Member와 연관을 시킬 가능성을 염두해두고 컬럼명을 설정해두었습니다!

2024-01-23 07:57 UTC, Hwanvely commented on src/main/java/com/snackgame/server/member/controller/AuthController.java
>          TokenDto reissued = tokenService.reissueFrom(refreshToken);
🫡

2024-01-23 07:57 UTC, Hwanvely commented on src/main/java/com/snackgame/server/member/controller/AuthController.java
> +                                .maxAge(0)
아! 또하나 배워갑니다 ㅎㅎ

2024-01-23 08:14 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/TokenService.java
> +    }
delete refreshToken 도 말이 어색하지 않아서 delete 정도로 괜찮을 것 같습니다!

2024-01-23 08:16 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
> +    @Column(name = "refresh_token_id", updatable = false)
멤버와 연관이 되어서 다른 테이블에서 접근하더라도 `refresh_token.id` <- 이런식으로 접근이 가능할 것 같아요.
이 정도면 의미 전달이 충분히 될 것 같습니다!

2024-01-23 08:46 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
> +    private boolean deleted = Boolean.FALSE;
JPA가 도메인 객체를 어떻게 만들어 줄까요?
그리고 그 과정에서 `boolean`과 `Boolean`에는 어떤 차이가 있을까요?
한 번 학습해보고 결정해도 좋을 것 같습니다.

2024-01-24 10:31 UTC, 0chil commented on src/main/java/com/snackgame/server/auth/token/domain/RefreshToken.java
> +    private boolean deleted = Boolean.FALSE;
선요약:
DDL 제약조건이 누락된 경우 런타임에 오류가 발생할 수도 있다.
하지만 `spring.jpa.hibernate.ddl-auto=validate`을 사용해주면 문제 없다.

---
문법적으로 `Boolean`은 **래퍼 클래스**이므로 널을 담을 수 있고, `boolean` 은 **원시 타입**이므로 널을 담을 수 없습니다.
이런 특성을 반영해 JPA는 원시 타입인 경우 `NOT NULL` 제약 조건을 붙여서 DDL을 생성하고 있어요.
그러면 `Boolean`과 `boolean` 사이에는 '`NOT NULL` 제약 조건이 붙는가?'에 대한 차이가 있다고 할 수 있겠네요.

---
하지만 이것만 믿을 순 없습니다.

보통 운영 서버에는 안전을 위해 DDL을 수동으로 배포하곤 하는데요.
가끔 휴먼 에러로 제약 조건이 빠질 수도 있습니다.

그러면 원시 타입에 null을 할당할 수 없어서 런타임에 다음과 같은 오류를 만날 수 있어요:
> Null value was assigned to a property [class com.snackgame.server.auth.token.domain.RefreshToken.deleted] of primitive type setter of com.snackgame.server.auth.token.domain.RefreshToken.deleted; nested exception is org.hibernate.PropertyAccessException: Null value was assigned to a property [class com.snackgame.server.auth.token.domain.RefreshToken.deleted] of primitive type setter of com.snackgame.server.auth.token.domain.RefreshToken.deleted

잘 배포된 줄 알았는데 갑자기 이런 오류가 뜨면 당황스럽겠죠?
다행히 `spring.jpa.hibernate.ddl-auto=validate`를 사용해, 어플리케이션 실행 단계에서 DDL을 검증하도록 할 수 있다고 하네요.
스낵게임 서버의 경우에는 여기서 문제가 검출되면 배포가 자동으로 취소되어 안전할 것 같습니다!

저도 설명해드리려고 쓰다보니 새로 알게된 사실이 많네요.
큰 문제는 없어서 학습 키워드 몇 개 남기고 PR 머지하겠습니다:
- 래퍼 클래스/원시 타입의 차이, 언제 사용해야 할지?
- Hibernate ddl-auto, validate 옵션

2024-01-24 10:32 UTC, 0chil approved these changes
고생하셨슴다~!

2024-01-24 10:32 UTC, merged